@Host=http://localhost:8080

### Actuator Endpoint
GET {{ Host }}/actuator

### Actuator Health Check
GET {{ Host }}/actuator/health

### Actuator Health ping Check
GET {{ Host }}/actuator/health/ping

### Actuator Health liveness Check
GET {{ Host }}/actuator/health/liveness

### Actuator Health Readiness Check
GET {{ Host }}/actuator/health/readiness

### query
# @name query
POST {{Host}}/api/athena/query
Content-Type: application/json

{
    "year": "2026",
    "month": "01",
    "day": "01",
    "userId": "user_001"
}

### status
GET {{Host}}/api/athena/status/{{query.response.body.queryExecutionId}}

### results
GET {{Host}}/api/athena/results/{{query.response.body.queryExecutionId}}

### results(stream)
GET {{Host}}/api/athena/download/{{query.response.body.queryExecutionId}}

### download url
GET {{Host}}/api/athena/download/{{query.response.body.queryExecutionId}}/url
