@Host=http://localhost:8080

### query
# @name query
POST {{Host}}/api/athena/query
Content-Type: application/json

{
    "year": "2026",
    "month": "01",
    "day": "01",
    "userId": "user_001"
}

### status
GET {{Host}}/api/athena/status/{{query.response.body.queryExecutionId}}

### results
GET {{Host}}/api/athena/results/{{query.response.body.queryExecutionId}}

### results(stream)
GET {{Host}}/api/athena/download/{{query.response.body.queryExecutionId}}

### download url
GET {{Host}}/api/athena/download/{{query.response.body.queryExecutionId}}/url
