spring:
  application:
    name: aws-athena-api-demo

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost}

aws:
  profile: ${AWS_PROFILE:default}
  athena:
    region: ${AWS_ATHENA_REGION:ap-northeast-1}
    database: ${AWS_ATHENA_DATABASE:audit_log_db}
    table: ${AWS_ATHENA_TABLE:audit_logs}
    output-location: ${AWS_ATHENA_OUTPUT_LOCATION:s3://athena-results-gekal-ap-northeast-1/results/}
  apigateway:
    # AWS API Gateway VPCリンクのID（例：vqxxxx）
    vpc-link-id: "vqxxxx"
    # ALBの内部DNSドメイン（http:// または https:// を含め、末尾の / は含めない）
    alb-uri: "http://internal-my-app-alb-123456789.ap-northeast-1.elb.amazonaws.com"

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: true
  packages-to-scan: cn.gekal.sample.awsathenaapidemo.interfaces.controller
